### PR TITLE
3.3.0.rc1

### PR DESCRIPTION
**Pull request by jhovad**
My update of this extension working fine for me with Spree 3.3.0.rc1 ... I'm not so advanced in Spree/Rails yet, but maybe it can helps someone.

### CODE REVIEW

**Comment by delphaber** [comment]
spree_i18n is now at 3.3.0.rc1 version. Can you update your gemspec too?

**Comment by jhovad** [comment]
I have tried to update it, but I'm probably not able to solve dependency problem in travis-ci ... :-(

**Comment by damianlegawiec** [comment]
@jhovad we'll be fixing this extension for Spree 3.1+ in coming days leading to final 3.3.0 release, thank you for your hard work, it will be much easier for us 👍

**Comment by damianlegawiec** [comment]
Done via https://github.com/spree-contrib/spree_globalize/pull/33

**Pull request closed without merging**
